#PBS -S /bin/bash
#PBS -m bea
#PBS -l select=8:ncpus=1:mem=16gb -l place=free
#PBS -l cput=24:00:00
#PBS -l walltime=32:00:00
#PBS -N getgilists
#PBS -o /work2/vallender/Projects/Hall-Project/DocsAndFiles/Logs/getgilists.o${PBS_JOBID}
#PBS -e /work2/vallender/Projects/Hall-Project/DocsAndFiles/Logs/getgilists.e${PBS_JOBID}
#PBS -j oe
cd ${PBS_O_WORKDIR}
python3 /work2/vallender/Projects/Hall-Project/Scripts/get_gi_lists.py
echo "End of script. Check your output."