# Read the Docs configuration for OrthoEvolution
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  jobs:
    pre_build:
      # Pre-build job: Run update_docs.py to regenerate API docs and convert READMEs
      # This runs before Sphinx builds the documentation
      - python docs/update_docs.py --skip-build

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements-docs.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/docs/source/conf.py
