Database_config:
  email: "researcher@example.org"
  driver: "sqlite3"
  Full:
    NCBI:
      NCBI_blast:
        NCBI_blast_db: {}
      NCBI_pub_taxonomy: {}
      NCBI_refseq_release:
        seqtype: "rna"
        seqformat: "gbff"
        collection_subset: "vertebrate_mammalian"
        configure_flag: True
        download_flag: True
        template_flag: True
    ITIS:
      ITIS_taxonomy: {}
