# Date Created: Tue Apr 16 2017
# Project Name: Orthologs Project
# This bash script using the blastn task to create XML blast results
# and then processes the output into a csv file which is analyzed.

#PBS -S /bin/bash
#PBS -m bea
#PBS -l select=8:ncpus=1:mem=16gb -l place=free
#PBS -l cput=100:00:00
#PBS -l walltime=100:00:00
#PBS -N blastn2csv
#PBS -o logs/blastn2csv.o${PBS_JOBID}
#PBS -e logs/blastn2csv.e${PBS_JOBID}

cd ${PBS_O_WORKDIR}

python3 blastn_to_csv.py