Management:
  Cookies : Path(pkg_resources.resource_filename(Cookies.__name__, ''))
  repo_cookie : Cookies / Path('new_repository')
  user_cookie : Cookies / Path('new_user')
  project_cookie : Cookies / Path('new_project')
  research_cookie : Cookies / Path('new_research')
  app_cookie : Cookies / Path('new_app')
  db_cookie : Cookies / Path('new_database')
  website_cookie : Cookies / Path('new_website')
  Manager : Path(pkg_resources.resource_filename(Manager.__name__, ''))
  index : Manager / Path('index')
  logit : Manager / Path('logit')
  utils : Manager / Path('utils')
  shiny : Manager / Path('shiny')
  Orthologs : Path(pkg_resources.resource_filename(Orthologs.__name__, ''))
  biosql : Orthologs / Path('biosql')
  blast : Orthologs / Path('blast')
  comp_gen : Orthologs / Path('comparative_genetics')
  genbank : Orthologs / Path('genbank')
  manager : Orthologs / Path('manager')
  phylogenetics : Orthologs / Path('phylogenetics')
  Tools : Path(pkg_resources.resource_filename(Tools.__name__, ''))
  ftp : Tools / Path('ftp')
  multiprocessing : Tools / Path('multiprocessing')
  pandoc : Tools / Path('pandoc')
  pybasher : Tools / Path('pybasher')
  qsub : Tools / Path('qsub')

  RepositoryManagement:
    UserManagement:
      ProjectManagement:
    WebManagement:

DataManagment:

DatabaseManagement:

CompGenObjects:
  CompGenFiles:
    CompGenBLASTn:

GenBank:

MultipleSequenceAlignment:

